
services:
  postgres:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "dac"
      POSTGRES_USER: "dac"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"