version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_dac
    environment:
      POSTGRES_DB: dac
      POSTGRES_USER: dac
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: